In [13]:
f = open("dontpatronizeme_categories.tsv", "r")

In [14]:
print(f.read())

------------------------------------------------------ DISCLAIMER ------------------------------------------------------
The Don’t Patronize Me! dataset has been created for research purposes. Patronizing and Condescending Language (PCL) towards vulnerable communities is understood in this dataset as a commonly used, generally unconscious and well intended writing style. We consider that the authors of the paragraphs included in this dataset do not intend any harm towards the vulnerable communities they talk about and we reckon that their objective is to support these communities and/or raise awareness towards difficult situations. The Don’t Patronize Me! dataset can only be used for research purposes.
------------------------------------------------------------------------------------------------------------------------

4046	@@14767805	We also know that they can benefit by receiving counseling from someone who can help them understand that their feelings are normal and that their

In [2]:
import random
import os
from urllib import request

In [16]:
module_url = f"https://raw.githubusercontent.com/Perez-AlmendrosC/dontpatronizeme/master/semeval-2022/dont_patronize_me.py"
module_name = module_url.split('/')[-1]
print(f'Fetching {module_url}')
#with open("file_1.txt") as f1, open("file_2.txt") as f2
with request.urlopen(module_url) as f, open(module_name,'w') as outf:
  a = f.read()
  outf.write(a.decode('utf-8'))

Fetching https://raw.githubusercontent.com/Perez-AlmendrosC/dontpatronizeme/master/semeval-2022/dont_patronize_me.py


In [1]:
from dont_patronize_me import DontPatronizeMe

In [3]:
from dont_patronize_me import DontPatronizeMe
# Initialize a dpm (Don't Patronize Me) object.
# It takes two areguments as input: 
# (1) Path to the directory containing the training set files, which is the root directory of this notebook.
# (2) Path to the test set, which will be released when the evaluation phase begins. In this example, 
# we use the dataset for Subtask 1, which the code will load without labels.
dpm = DontPatronizeMe('.', 'dontpatronizeme_pcl.tsv')

In [4]:
dpm

In [5]:
# This method loads the subtask 1 data
dpm.load_task1()

In [6]:
# which we can then access as a dataframe
dpm.train_task1_df.head()

par_id      art_id    keyword country  \
0      1  @@24942188   hopeless      ph   
1      2  @@21968160    migrant      gh   
2      3  @@16584954  immigrant      ie   
3      4   @@7811231   disabled      nz   
4      5   @@1494111    refugee      ca   

                                                text  label orig_label  
0  We 're living in times of absolute insanity , ...      0          0  
1  In Libya today , there are countless number of...      0          0  
2  "White House press secretary Sean Spicer said ...      0          0  
3  Council customers only signs would be displaye...      0          0  
4  """ Just like we received migrants fleeing El ...      0          0

In [7]:
dpm.train_task1_df

par_id      art_id     keyword country  \
0          1  @@24942188    hopeless      ph   
1          2  @@21968160     migrant      gh   
2          3  @@16584954   immigrant      ie   
3          4   @@7811231    disabled      nz   
4          5   @@1494111     refugee      ca   
...      ...         ...         ...     ...   
10464  10465  @@14297363       women      lk   
10465  10466  @@70091353  vulnerable      ph   
10466  10467  @@20282330     in-need      ng   
10467  10468  @@16753236    hopeless      in   
10468  10469  @@16779383    homeless      ie   

                                                    text  label orig_label  
0      We 're living in times of absolute insanity , ...      0          0  
1      In Libya today , there are countless number of...      0          0  
2      "White House press secretary Sean Spicer said ...      0          0  
3      Council customers only signs would be displaye...      0          0  
4      """ Just like we received migrants fleeing El ...      0          0  
...                                                  ...    ...        ...  
10464  "Sri Lankan norms and culture inhibit women fr...      0          1  
10465  He added that the AFP will continue to bank on...      0          0  
10466  """ She has one huge platform , and informatio...      1          3  
10467  """ Anja Ringgren Loven I ca n't find a word t...      1          4  
10468  """ Guinness World Record of 540lbs of 7-layer...      1          3  

[10469 rows x 7 columns]

In [8]:
dpm.train_task1_df['label'].value_counts() # highly imbalenced data

0    9476
1     993
Name: label, dtype: int64

In [9]:
dpm.train_task1_df['orig_label'].value_counts()

0    8529
1     947
3     458
4     391
2     144
Name: orig_label, dtype: int64

In [10]:
dpm.train_task1_df.iloc[10464,:]

par_id                                                    10465
art_id                                               @@14297363
keyword                                                   women
country                                                      lk
text          "Sri Lankan norms and culture inhibit women fr...
label                                                         0
orig_label                                                    1
Name: 10464, dtype: object

In [11]:
dpm.train_task1_df.iloc[0,:]

par_id                                                        1
art_id                                               @@24942188
keyword                                                hopeless
country                                                      ph
text          We 're living in times of absolute insanity , ...
label                                                         0
orig_label                                                    0
Name: 0, dtype: object

In [12]:
dpm.train_task1_df['text'][0]

"We 're living in times of absolute insanity , as I 'm pretty sure most people are aware . For a while , waking up every day to check the news seemed to carry with it the same feeling of panic and dread that action heroes probably face when they 're trying to decide whether to cut the blue or green wire on a ticking bomb -- except the bomb 's instructions long ago burned in a fire and imminent catastrophe seems the likeliest outcome . It 's hard to stay that on-edge for that long , though , so it 's natural for people to become inured to this constant chaos , to slump into a malaise of hopelessness and pessimism ."

In [13]:
# dpm.train_task1_df.to_csv("dontpatronizeme.csv")

In [14]:
dpm.train_task1_df.columns   #.iloc['text','orig_label']

Index(['par_id', 'art_id', 'keyword', 'country', 'text', 'label',
       'orig_label'],
      dtype='object')

In [15]:
# dpm.train_task1_df.columns.iloc[4:]

# Dontpatronizeme.csv

In [16]:
import pandas as pd

In [17]:
data  = pd.read_csv('dontpatronizeme.csv')

In [18]:
data.head()

Unnamed: 0  par_id      art_id    keyword country  \
0           0       1  @@24942188   hopeless      ph   
1           1       2  @@21968160    migrant      gh   
2           2       3  @@16584954  immigrant      ie   
3           3       4   @@7811231   disabled      nz   
4           4       5   @@1494111    refugee      ca   

                                                text  label  orig_label  
0  We 're living in times of absolute insanity , ...      0           0  
1  In Libya today , there are countless number of...      0           0  
2  "White House press secretary Sean Spicer said ...      0           0  
3  Council customers only signs would be displaye...      0           0  
4  """ Just like we received migrants fleeing El ...      0           0

In [19]:
df = data.iloc[:,5:]

In [20]:
df

text  label  orig_label
0      We 're living in times of absolute insanity , ...      0           0
1      In Libya today , there are countless number of...      0           0
2      "White House press secretary Sean Spicer said ...      0           0
3      Council customers only signs would be displaye...      0           0
4      """ Just like we received migrants fleeing El ...      0           0
...                                                  ...    ...         ...
10464  "Sri Lankan norms and culture inhibit women fr...      0           1
10465  He added that the AFP will continue to bank on...      0           0
10466  """ She has one huge platform , and informatio...      1           3
10467  """ Anja Ringgren Loven I ca n't find a word t...      1           4
10468  """ Guinness World Record of 540lbs of 7-layer...      1           3

[10469 rows x 3 columns]

In [21]:
df

text  label  orig_label
0      We 're living in times of absolute insanity , ...      0           0
1      In Libya today , there are countless number of...      0           0
2      "White House press secretary Sean Spicer said ...      0           0
3      Council customers only signs would be displaye...      0           0
4      """ Just like we received migrants fleeing El ...      0           0
...                                                  ...    ...         ...
10464  "Sri Lankan norms and culture inhibit women fr...      0           1
10465  He added that the AFP will continue to bank on...      0           0
10466  """ She has one huge platform , and informatio...      1           3
10467  """ Anja Ringgren Loven I ca n't find a word t...      1           4
10468  """ Guinness World Record of 540lbs of 7-layer...      1           3

[10469 rows x 3 columns]

In [24]:
df['label'].value_counts()  # highly imbalenced data

0    9476
1     993
Name: label, dtype: int64

#### The experiments reported in the paper consider the following tag grouping: 
	- {0,1}   = No PCL
	- {2,3,4} = PCL

In [8]:
df['orig_label'].value_counts()

0    8529
1     947
3     458
4     391
2     144
Name: orig_label, dtype: int64

In [25]:
 8529 + 947

9476

In [26]:
df['text'][0]

"We 're living in times of absolute insanity , as I 'm pretty sure most people are aware . For a while , waking up every day to check the news seemed to carry with it the same feeling of panic and dread that action heroes probably face when they 're trying to decide whether to cut the blue or green wire on a ticking bomb -- except the bomb 's instructions long ago burned in a fire and imminent catastrophe seems the likeliest outcome . It 's hard to stay that on-edge for that long , though , so it 's natural for people to become inured to this constant chaos , to slump into a malaise of hopelessness and pessimism ."

In [27]:
df2 = data.iloc[:,5:-1]

In [28]:
df2

text  label
0      We 're living in times of absolute insanity , ...      0
1      In Libya today , there are countless number of...      0
2      "White House press secretary Sean Spicer said ...      0
3      Council customers only signs would be displaye...      0
4      """ Just like we received migrants fleeing El ...      0
...                                                  ...    ...
10464  "Sri Lankan norms and culture inhibit women fr...      0
10465  He added that the AFP will continue to bank on...      0
10466  """ She has one huge platform , and informatio...      1
10467  """ Anja Ringgren Loven I ca n't find a word t...      1
10468  """ Guinness World Record of 540lbs of 7-layer...      1

[10469 rows x 2 columns]

In [29]:
df2['text'][0]

"We 're living in times of absolute insanity , as I 'm pretty sure most people are aware . For a while , waking up every day to check the news seemed to carry with it the same feeling of panic and dread that action heroes probably face when they 're trying to decide whether to cut the blue or green wire on a ticking bomb -- except the bomb 's instructions long ago burned in a fire and imminent catastrophe seems the likeliest outcome . It 's hard to stay that on-edge for that long , though , so it 's natural for people to become inured to this constant chaos , to slump into a malaise of hopelessness and pessimism ."

In [30]:
df2['text'][5]

'To bring down high blood sugar levels , insulin needs to be taken . If you are the type who requires insulin during meal time , you will have to take correct doses of insulin in order to lower your blood glucose . Decision needs to be taken on when to inject it and how many times to inject . For this , you have to take the help of a health care professional .'

In [31]:
len(df2['text'][0])

620

In [32]:
ddf  = df2['text'].values

In [33]:
ddf.shape

(10469,)

In [34]:
type(ddf)

numpy.ndarray

# Word Embedding Representations

In [35]:
from tensorflow.keras.layers import Embedding     # fpr word embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences   # for Padding
from tensorflow.keras.models import Sequential    # for creating the sequential model layers
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot  # helps us to do one hot encodding

In [36]:
import nltk
import re
from nltk.corpus import stopwords

In [37]:
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [38]:
len(df2)

10469

In [39]:
type(df2['text'][0])

str

In [40]:
len(ddf)

10469

In [41]:
dff = df2.iloc[:5000,:]

In [42]:
dff

text  label
0     We 're living in times of absolute insanity , ...      0
1     In Libya today , there are countless number of...      0
2     "White House press secretary Sean Spicer said ...      0
3     Council customers only signs would be displaye...      0
4     """ Just like we received migrants fleeing El ...      0
...                                                 ...    ...
4995  Food for Empowerment in Emergencies and Disast...      0
4996  Crooks said she is appealing to persons to be ...      1
4997  """ This would constitute a valuable step towa...      0
4998  So , is Metro Vancouver any better today at ac...      0
4999  One of the militia , Dickson Mdachi , told the...      0

[5000 rows x 2 columns]

In [43]:
# TypeError: expected string or bytes-like object

In [44]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(dff)):
    review = re.sub('[^a-zA-Z]', " ", dff['text'][i] or " ")
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [45]:
corpus

['live time absolut insan pretti sure peopl awar wake everi day check news seem carri feel panic dread action hero probabl face tri decid whether cut blue green wire tick bomb except bomb instruct long ago burn fire immin catastroph seem likeliest outcom hard stay edg long though natur peopl becom inur constant chao slump malais hopeless pessim',
 'libya today countless number ghanaian nigerian immigr two countri key macroeconom challeng includ unemploy let tackl issu root fruit thank',
 'white hous press secretari sean spicer said focu immigr action would illeg immigr also otherwis violat law',
 'council custom sign would display two space would reserv disabl person would five p space eight p one',
 'like receiv migrant flee el salvador guatemala like seen thousand econom refuge start see mexican flee violenc ju rez part mexico say shelter director ruben garcia',
 'bring high blood sugar level insulin need taken type requir insulin meal time take correct dose insulin order lower blood

In [46]:
corpus[1]

'libya today countless number ghanaian nigerian immigr two countri key macroeconom challeng includ unemploy let tackl issu root fruit thank'

In [47]:
df2['text'][0]

"We 're living in times of absolute insanity , as I 'm pretty sure most people are aware . For a while , waking up every day to check the news seemed to carry with it the same feeling of panic and dread that action heroes probably face when they 're trying to decide whether to cut the blue or green wire on a ticking bomb -- except the bomb 's instructions long ago burned in a fire and imminent catastrophe seems the likeliest outcome . It 's hard to stay that on-edge for that long , though , so it 's natural for people to become inured to this constant chaos , to slump into a malaise of hopelessness and pessimism ."

In [48]:
# one Hot representation
voc_size = 5000
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[4304,
  4371,
  173,
  1778,
  3162,
  1165,
  4771,
  733,
  2390,
  1752,
  3093,
  2904,
  352,
  1492,
  2357,
  4023,
  3476,
  3507,
  1134,
  897,
  3707,
  200,
  1725,
  1297,
  2895,
  743,
  73,
  1063,
  737,
  4763,
  507,
  4467,
  507,
  4121,
  2189,
  3847,
  2393,
  2245,
  2570,
  722,
  1492,
  3600,
  3840,
  1463,
  489,
  1560,
  2189,
  4843,
  4347,
  4771,
  1894,
  3827,
  2839,
  538,
  3649,
  2098,
  1020,
  1565],
 [2053,
  2534,
  3351,
  4520,
  2041,
  1595,
  3971,
  4328,
  3693,
  4250,
  2479,
  4268,
  4208,
  584,
  4257,
  2742,
  3777,
  91,
  3525,
  2951],
 [599,
  249,
  309,
  2854,
  3983,
  4394,
  3070,
  1456,
  3971,
  1134,
  2887,
  1095,
  3971,
  4604,
  2439,
  2167,
  644],
 [1680,
  332,
  2852,
  2887,
  2663,
  4328,
  4412,
  2887,
  2499,
  3538,
  4612,
  2887,
  3310,
  1444,
  4412,
  2857,
  1444,
  3779],
 [801,
  4088,
  3033,
  539,
  499,
  4224,
  1583,
  801,
  2664,
  2345,
  4997,
  4996,
  4729,
  4212,
  2771

In [49]:
onehot_repr[1]

[2053,
 2534,
 3351,
 4520,
 2041,
 1595,
 3971,
 4328,
 3693,
 4250,
 2479,
 4268,
 4208,
 584,
 4257,
 2742,
 3777,
 91,
 3525,
 2951]

In [50]:
sent_length=35
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)  # to make sure that every sentence should have same length
print(embedded_docs)

[[1297 2895  743 ... 2098 1020 1565]
 [2053 2534 3351 ...    0    0    0]
 [ 599  249  309 ...    0    0    0]
 ...
 [2887 4064 3519 ...    0    0    0]
 [1584 1906 2562 ...    0    0    0]
 [3779  271 3888 ...    0    0    0]]


In [51]:
embedded_docs[9]

array([4674, 3070, 1898, 1864, 2174, 1911, 3746, 4604, 3070, 1911, 3364,
       3791, 1786, 1171, 3232, 1650, 1498, 2887,  309, 4875, 2339,  178,
       1960, 2562, 1911, 1615,  672, 2629,    0,    0,    0,    0,    0,
          0,    0])

In [52]:
from tensorflow.keras.layers import Embedding  # like word2vec implementaion
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [53]:
## Creating model
embedding_vector_features=40 ##features representation # each and every word now going to convert in vector of 40 size,40 feature it may have
model=Sequential()     # each word represent 40 diffrent features
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))   # LSTM with 100 neurons   
model.add(Dense(1,activation='sigmoid'))   #
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())  # when ever my output is binary we use binary crossentropy, optimaization

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 35, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [54]:
dff['label'].value_counts()

0    4535
1     465
Name: label, dtype: int64

In [55]:
y = dff['label']

In [56]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    1
4997    0
4998    0
4999    0
Name: label, Length: 5000, dtype: int64

In [57]:
len(embedded_docs),y.shape

(5000, (5000,))

In [58]:
type(y)

pandas.core.series.Series

In [59]:
type(embedded_docs)

numpy.ndarray

In [60]:
import numpy as np
X_final=np.array(embedded_docs)
y_final= np.array(y)

In [61]:
X_final.shape,y_final.shape

((5000, 35), (5000,))

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [63]:
### Finally Training
model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=10,batch_size=64) 

Epoch 1/10
53/53 [==============================] - 4s 35ms/step - loss: 0.3697 - accuracy: 0.9060 - val_loss: 0.3233 - val_accuracy: 0.9042
Epoch 2/10
53/53 [==============================] - 1s 25ms/step - loss: 0.2889 - accuracy: 0.9087 - val_loss: 0.2966 - val_accuracy: 0.9042
Epoch 3/10
53/53 [==============================] - 1s 25ms/step - loss: 0.1936 - accuracy: 0.9373 - val_loss: 0.3578 - val_accuracy: 0.8909
Epoch 4/10
53/53 [==============================] - 1s 24ms/step - loss: 0.1172 - accuracy: 0.9642 - val_loss: 0.3235 - val_accuracy: 0.8855
Epoch 5/10
53/53 [==============================] - 1s 25ms/step - loss: 0.0696 - accuracy: 0.9854 - val_loss: 0.5139 - val_accuracy: 0.8806
Epoch 6/10
53/53 [==============================] - 1s 24ms/step - loss: 0.0496 - accuracy: 0.9896 - val_loss: 0.3536 - val_accuracy: 0.8867
Epoch 7/10
53/53 [==============================] - 1s 25ms/step - loss: 0.0343 - accuracy: 0.9931 - val_loss: 0.4809 - val_accuracy: 0.8958
Epoch 8/10
53

In [64]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [65]:
y_pred=model.predict(X_test)

52/52 [==============================] - 1s 6ms/step


In [66]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [67]:
from sklearn.metrics import confusion_matrix

In [68]:
confusion_matrix(y_test,y_pred)

array([[1492,    0],
       [ 158,    0]], dtype=int64)

In [69]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9042424242424243

In [70]:
dff['label'].value_counts()

0    4535
1     465
Name: label, dtype: int64

In [71]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1492
           1       0.00      0.00      0.00       158

    accuracy                           0.90      1650
   macro avg       0.45      0.50      0.47      1650
weighted avg       0.82      0.90      0.86      1650



C:\Users\panka\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\panka\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\panka\anaconda3\envs\nlp\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
Problems :
    1. Data Imbalenced 